version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: joy-it_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - ./data/database/redis:/data
    ports:
      - 6379:6379
    networks:
      - local_network

  postgres:
    image: postgres:alpine
    container_name: joy-it_postgres
    environment:
      POSTGRESQL_DATABASE: ${DB_NAME_DEV}
      POSTGRESQL_USERNAME: ${DB_USER}
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data/database/postgres:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    networks:
      - local_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: joy-it_backend
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis
      - postgres
    networks:
      - local_network

volumes:
  redis_data:
  postgres_data:

networks:
  local_network:
