name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - run: |
          sudo chmod -R u+rw /home/souheib/runners/joy-it-backend/_work/joy-it-backend/joy-it-backend/
          sudo rm -rf /home/souheib/runners/joy-it-backend/_work/joy-it-backend/joy-it-backend/*
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: npm install
      - run: npm run build --if-present
      - run: pm2 restart joy-it-backend
