name: Backend CI and Lint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Run Lint
        run: npm run lint

  ci:
    needs: lint # Ensures CI runs after lint
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main' # Restrict CI to main branch
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      - run: |
          chmod -R u+rw /home/souheib/runners/backend/_work/joy-it-backend/joy-it-backend
          rm -rf /home/souheib/runners/backend/_work/joy-it-backend/joy-it-backend/node_modules
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag the Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_REPOSITORY }}:latest .

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_REPOSITORY }}:latest

      - name: Apply changes
        run: kubectl rollout restart deploy joy-it-backend -n joy-it
