name: CI

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
      # - run: |
      #     chmod -R u+rw /home/souheib/runners/joy-it-backend/_work/joy-it-backend/joy-it-backend/
      #     rm -rf /home/souheib/runners/joy-it-backend/_work/joy-it-backend/joy-it-backend/node_modules
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: |
          touch .env
          echo "${{ secrets.ENV_FILE }}" > .env
      # - run: pm2 restart joy-it-backend
